<?php

return [
    'sender' => [
        'name' => env('BREVO_SENDER_NAME', config('app.name', 'BrandBeacon')),
        'email' => env('BREVO_SENDER_EMAIL', config('mail.from.address', 'hello@example.com')),
    ],
    'logo_url' => env('BREVO_LOGO_URL', rtrim((string) config('app.url'), '/').'/brand-beacon-logo.png'),
    'search_done_enabled' => env('BREVO_SEARCH_DONE_ENABLED', env('APP_ENV', 'production') !== 'local'),

    'notifications' => [
        'new_registration' => [
            'sources' => ['user'],
            'params' => ['dashboardUrl', 'firstName', 'fullName', 'loginUrl', 'plansUrl'],
            'preview' => 'Your free search is ready when you are',
            'label' => 'Account created',
            'subject' => 'Your account is ready. Let’s find your next winning creative.',
            'template_id' => env('BREVO_TEMPLATE_ID_NEW_REGISTRATION'),
            'tags' => ['registration', 'lifecycle'],
        ],
        'subscription_started' => [
            'sources' => ['user', 'subscription'],
            'params' => ['accessEndsAt', 'dashboardUrl', 'firstName', 'fullName', 'isTrial', 'planName', 'planSlug', 'renewalLabel', 'savedSearchesUrl', 'searchBookmarkLimit', 'searchLimit', 'settingsUrl', 'videoAnalysisLimit', 'videoBookmarkLimit'],
            'preview' => 'What to set up first',
            'label' => 'Subscription started',
            'subject' => 'Your plan is live. Here’s what you can do now.',
            'template_id' => env('BREVO_TEMPLATE_ID_SUBSCRIPTION_STARTED'),
            'tags' => ['subscription', 'billing'],
        ],
        'subscription_canceled' => [
            'sources' => ['user', 'subscription'],
            'params' => ['accessEndsAt', 'dashboardUrl', 'firstName', 'fullName', 'planName', 'plansUrl', 'supportEmail'],
            'preview' => 'Access continues until {{accessEndsAt}}',
            'label' => 'Subscription canceled',
            'subject' => 'Your plan has been canceled',
            'template_id' => env('BREVO_TEMPLATE_ID_SUBSCRIPTION_CANCELED'),
            'tags' => ['subscription', 'cancellation'],
        ],
        'verify_email_manual_account' => [
            'sources' => ['user'],
            'params' => ['expiresInDays', 'firstName', 'fullName', 'supportEmail', 'verifyUrl'],
            'preview' => 'One tap to activate your account',
            'label' => 'Verify email address',
            'subject' => 'Verify your email to activate your account',
            'template_id' => env('BREVO_TEMPLATE_ID_VERIFY_EMAIL_MANUAL_ACCOUNT'),
            'tags' => ['verification', 'account'],
        ],
        'trial_ending_cc' => [
            'sources' => ['user', 'subscription'],
            'params' => ['dashboardUrl', 'daysRemaining', 'firstName', 'fullName', 'planName', 'plansUrl', 'settingsUrl', 'trialEndsAt'],
            'preview' => '{{daysRemaining}} days left',
            'label' => 'Trial ending (card on file)',
            'subject' => 'Your trial is ending soon',
            'template_id' => env('BREVO_TEMPLATE_ID_TRIAL_ENDING'),
            'tags' => ['trial', 'billing'],
        ],
        'payment_failed_first' => [
            'sources' => ['user', 'subscription'],
            'params' => ['attempt', 'billingUrl', 'dashboardUrl', 'firstName', 'fullName', 'nextAttemptAt', 'planName', 'supportEmail'],
            'preview' => 'Nothing has changed yet',
            'label' => 'Card declined (1st attempt)',
            'subject' => 'Your card did not go through',
            'template_id' => env('BREVO_TEMPLATE_ID_PAYMENT_FAILED_FIRST'),
            'tags' => ['billing', 'payment-failed', 'dunning'],
        ],
        'payment_failed_second' => [
            'sources' => ['user', 'subscription'],
            'params' => ['attempt', 'billingUrl', 'dashboardUrl', 'firstName', 'fullName', 'nextAttemptAt', 'planName', 'supportEmail'],
            'preview' => 'Second attempt declined',
            'label' => 'Card declined (2nd attempt)',
            'subject' => 'Still having trouble with your card',
            'template_id' => env('BREVO_TEMPLATE_ID_PAYMENT_FAILED_SECOND'),
            'tags' => ['billing', 'payment-failed', 'dunning'],
        ],
        'card_expiring' => [
            'sources' => ['user', 'subscription'],
            'params' => ['billingUrl', 'cardBrand', 'cardExpiryDate', 'cardLast4', 'firstName', 'fullName', 'planName', 'supportEmail'],
            'preview' => '{{cardBrand}} ending {{cardLast4}}',
            'label' => 'Card expiring soon',
            'subject' => 'The card on file expires on {{cardExpiryDate}}',
            'template_id' => env('BREVO_TEMPLATE_ID_CARD_EXPIRING'),
            'tags' => ['billing', 'payment-method'],
        ],
        'final_failed_payment' => [
            'sources' => ['user', 'subscription'],
            'params' => ['accessEndedAt', 'contactUrl', 'dashboardUrl', 'firstName', 'fullName', 'planName', 'plansUrl', 'settingsUrl', 'supportEmail'],
            'preview' => 'Your saved work is kept',
            'label' => 'Final payment failure',
            'subject' => 'Your paid access is ending due to a final payment failure',
            'template_id' => env('BREVO_TEMPLATE_ID_FINAL_FAILED_PAYMENT'),
            'tags' => ['billing', 'payment-failed', 'downgrade'],
        ],
        'trial_ending_no_cc' => [
            'sources' => ['user', 'subscription'],
            'params' => ['dashboardUrl', 'daysRemaining', 'firstName', 'fullName', 'planName', 'plansUrl', 'settingsUrl', 'trialEndsAt'],
            'preview' => 'No card on file yet',
            'label' => 'Trial ending (no card on file)',
            'subject' => 'Add your card to keep paid access after your trial',
            'template_id' => env('BREVO_TEMPLATE_ID_NO_CC_TRIAL_ENDING'),
            'tags' => ['trial', 'billing', 'payment-method'],
        ],
        'onboarding_no_search' => [
            'sources' => ['user'],
            'params' => ['dashboardUrl', 'firstName', 'fullName', 'searchUrl'],
            'preview' => 'An example of what a Breakout Score catches',
            'transactional' => false,
            'label' => 'Signed up, no search yet',
            'subject' => 'Your free search is still waiting',
            'template_id' => env('BREVO_TEMPLATE_ID_ONBOARDING_NO_SEARCH'),
            'tags' => ['onboarding', 'activation'],
        ],
        'free_results_second_look' => [
            'sources' => ['user', 'search'],
            'params' => ['breakoutCount', 'firstName', 'fullName', 'plansUrl', 'resultsUrl', 'searchTerm', 'trialUrl'],
            'preview' => 'What repeats is what matters',
            'transactional' => false,
            'label' => 'Free results, second look',
            'subject' => '{{searchTerm}}, a second look',
            'template_id' => env('BREVO_TEMPLATE_ID_FREE_RESULTS_SECOND_LOOK'),
            'tags' => ['free', 'results'],
        ],
        'free_results_last_note' => [
            'sources' => ['user', 'search'],
            'params' => ['breakoutCount', 'firstName', 'fullName', 'plansUrl', 'resultsUrl', 'searchTerm', 'trialUrl'],
            'preview' => 'Last note on this search',
            'transactional' => false,
            'label' => 'Free results, last note',
            'subject' => 'Following up on your free search',
            'template_id' => env('BREVO_TEMPLATE_ID_FREE_RESULTS_LAST_NOTE'),
            'tags' => ['free', 'results', 'conversion'],
        ],
        'trial_breakout_score' => [
            'sources' => ['user', 'subscription'],
            'params' => ['dashboardUrl', 'firstName', 'fullName', 'libraryUrl', 'planName'],
            'preview' => 'Sort by score, not views',
            'label' => 'Trial day 2: Breakout Score',
            'subject' => 'How to use Breakout Score on your trial',
            'template_id' => env('BREVO_TEMPLATE_ID_TRIAL_BREAKOUT_SCORE'),
            'tags' => ['trial', 'education'],
        ],
        'trial_one_breakout' => [
            'sources' => ['user', 'subscription', 'search'],
            'params' => ['breakoutScore', 'dashboardUrl', 'firstName', 'fullName', 'resultsUrl', 'searchTerm', 'videoCaption', 'videoHandle', 'videoThumbnail', 'videoViews'],
            'preview' => 'The strongest thing you tracked',
            'label' => 'Trial day 7: one breakout',
            'subject' => 'One breakout from {{searchTerm}}',
            'template_id' => env('BREVO_TEMPLATE_ID_TRIAL_ONE_BREAKOUT'),
            'tags' => ['trial', 'engagement'],
        ],
        // --- Winback: trial lapsed without a purchase (flow 5) ---
        'trial_winback_ended' => [
            'sources' => ['user', 'subscription'],
            'params' => ['contactUrl', 'dashboardUrl', 'endedOn', 'firstName', 'fullName', 'libraryUrl', 'missedCount', 'planName', 'plansUrl'],
            'preview' => 'Your workspace is kept',
            'transactional' => false,
            'label' => 'Trial ended (day 1)',
            'subject' => 'Your 8-day trial ended',
            'template_id' => env('BREVO_TEMPLATE_ID_TRIAL_WINBACK_ENDED'),
            'tags' => ['winback', 'trial'],
        ],
        'trial_winback_missed' => [
            'sources' => ['user', 'subscription'],
            'params' => ['contactUrl', 'dashboardUrl', 'endedOn', 'firstName', 'fullName', 'libraryUrl', 'missedCount', 'planName', 'plansUrl'],
            'preview' => '{{missedCount}} since you left',
            'transactional' => false,
            'label' => 'Trial winback, missed breakouts (day 7)',
            'subject' => '{{missedCount}} breakouts since you left',
            'template_id' => env('BREVO_TEMPLATE_ID_TRIAL_WINBACK_MISSED'),
            'tags' => ['winback', 'trial'],
        ],
        'trial_winback_last_note' => [
            'sources' => ['user', 'subscription'],
            'params' => ['contactUrl', 'dashboardUrl', 'endedOn', 'firstName', 'fullName', 'libraryUrl', 'missedCount', 'planName', 'plansUrl'],
            'preview' => 'Last note, then we stop',
            'transactional' => false,
            'label' => 'Trial winback, last note (day 21)',
            'subject' => 'Last note about your trial',
            'template_id' => env('BREVO_TEMPLATE_ID_TRIAL_WINBACK_LAST_NOTE'),
            'tags' => ['winback', 'trial'],
        ],

        // --- Winback: a paying subscription ended (flow 6) ---
        'churn_winback_ended' => [
            'sources' => ['user', 'subscription'],
            'params' => ['contactUrl', 'dashboardUrl', 'endedOn', 'firstName', 'fullName', 'libraryUrl', 'missedCount', 'planName', 'plansUrl'],
            'preview' => 'Nothing has been deleted',
            'transactional' => false,
            'label' => 'Subscription ended (day 3)',
            'subject' => 'Your Brand Beacon subscription ended',
            'template_id' => env('BREVO_TEMPLATE_ID_CHURN_WINBACK_ENDED'),
            'tags' => ['winback', 'churn'],
        ],
        'churn_winback_missed' => [
            'sources' => ['user', 'subscription'],
            'params' => ['contactUrl', 'dashboardUrl', 'endedOn', 'firstName', 'fullName', 'libraryUrl', 'missedCount', 'planName', 'plansUrl'],
            'preview' => '{{missedCount}} since you cancelled',
            'transactional' => false,
            'label' => 'Churn winback, missed breakouts (day 14)',
            'subject' => '{{missedCount}} breakouts since you cancelled',
            'template_id' => env('BREVO_TEMPLATE_ID_CHURN_WINBACK_MISSED'),
            'tags' => ['winback', 'churn'],
        ],
        'churn_winback_last_note' => [
            'sources' => ['user', 'subscription'],
            'params' => ['contactUrl', 'dashboardUrl', 'endedOn', 'firstName', 'fullName', 'libraryUrl', 'missedCount', 'planName', 'plansUrl'],
            'preview' => 'Last note, then we stop',
            'transactional' => false,
            'label' => 'Churn winback, last note (day 45)',
            'subject' => 'Last note since you cancelled',
            'template_id' => env('BREVO_TEMPLATE_ID_CHURN_WINBACK_LAST_NOTE'),
            'tags' => ['winback', 'churn'],
        ],

        'biweekly_pack' => [
            'sources' => ['user', 'subscription'],
            'params' => ['breakoutCount', 'dashboardUrl', 'firstName', 'fullName', 'libraryUrl', 'pick1Caption', 'pick1Handle', 'pick1Score', 'pick1Subject', 'pick1Thumbnail', 'pick1Views', 'pick2Caption', 'pick2Handle', 'pick2Score', 'pick2Subject', 'pick2Thumbnail', 'pick2Views', 'pick3Caption', 'pick3Handle', 'pick3Score', 'pick3Subject', 'pick3Thumbnail', 'pick3Views', 'planName', 'since', 'topSubject'],
            'preview' => 'Three worth a look',
            'transactional' => false,
            'label' => 'Bi-weekly pack',
            'subject' => '{{breakoutCount}} breakouts worth a look',
            'template_id' => env('BREVO_TEMPLATE_ID_BIWEEKLY_PACK'),
            'tags' => ['digest', 'ongoing'],
        ],
        'weekly_digest' => [
            'sources' => ['user', 'subscription'],
            'params' => ['brandBreakouts', 'breakoutCount', 'dashboardUrl', 'firstName', 'fullName', 'libraryUrl', 'planName', 'productBreakouts', 'searchTerm', 'weekOf'],
            'preview' => '{{breakoutCount}} breakouts this week',
            'transactional' => false,
            'label' => 'Weekly digest',
            'subject' => '{{searchTerm}}, week of {{weekOf}}: {{breakoutCount}} viral breakouts',
            'template_id' => env('BREVO_TEMPLATE_ID_WEEKLY_DIGEST'),
            'tags' => ['digest', 'ongoing'],
        ],
        'search_done' => [
            'sources' => ['user', 'search'],
            'params' => ['breakoutCount', 'dashboardUrl', 'firstName', 'fullName', 'latestRunAt', 'resultsCount', 'resultsUrl', 'searchName', 'searchPhrase', 'searchTerm', 'searchType'],
            'preview' => '{{breakoutCount}} breakouts, ranked',
            'label' => 'Search results ready',
            'subject' => '{{searchTerm}}: {{breakoutCount}} viral breakouts found',
            'template_id' => env('BREVO_TEMPLATE_ID_SEARCH_DONE'),
            'tags' => ['search', 'results'],
        ],
    ],
];
